[package]
name = "html_parser"
version = "0.1.0"
edition = "2021"
description = "A simple parser for html files to extract tags, child tags, attributes, etc."
readme = "README.md"
repository = "https://github.com/KatyaStriletska/HtmlParser"

[dependencies]
pest = "2.7.14"
pest_derive = "2.7.14"